name: "Reusable-Flow"
on:
  workflow_call:
    secrets:
      KUBECONFIG:
        required: true
      MONGO_PASSWORD:
        required: true
    inputs:
      mongo-uri:
        required: true
        type: string
      environment:
        required: true
        type: string
        default: development
      manifest-path:
        required: true
        type: string
        default: "kubernetes/development/"
      k8s-version:
        required: false
        type: string
        default: "1.27.3"
    outputs:
      url-ingress-reusable:
        description: The Ingress URL
        value: ${{ jobs.reuse-deployment.outputs.url-ingress }}
jobs:
  reuse-deployment:
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.url-ingress.outputs.INGRESS_URL_HOST }}
    outputs:
      url-ingress: ${{ steps.url-ingress.outputs.INGRESS_URL_HOST }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        name: Setup KubeCtl
        id: install
      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      # - name: fetch k8s details
      #   run: |

      #     kubectl get nodes
      # - name: save INGRESS_IP
      #   run: |
      #     INGRESS_IP=$(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
      #     echo "INGRESS_IP=$INGRESS_IP" >> $GITHUB_ENV
      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "_{_"
          tokenSuffix: "_}_"
          files: '["${{inputs.manifest-path}}*"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          INGRESS_IP: ${{ env.INGRESS_IP }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKER_USER }}/solar-system:${{ github.sha }}
      - name: check files
        run: |
          cat${{inputs.manifest-path}}*.yaml
      # - name: create Mongo-secret
      #   run: |
      #     kubectl create secret generic mongo-db-creds -n ${{ vars.NAMESPACE }} \
      #     --from-literal=MONGO_URI=${{inputs.mongo-uri}} \
      #      --from-literal=MONGO_USERNAME=$MONGO_USERNAME \
      #      --from-literal=MONGO_PASSWORD=$MONGO_PASSWORD \
      #      --save-config \
      #      --dry-run=client -o yaml | kubectl apply -f -
      # - name: apply deployment to development namespace
      #   run: |
      #     kubectl apply -f ${{inputs.manifest-path}} -n ${{ vars.NAMESPACE }}
      # - name: set url for ingress
      #   id: url-ingress
      #   run: |
      #     echo "INGRESS_URL_HOST=$(kubectl get ingress -n ${{ vars.NAMESPACE }} solar-system -o jsonpath='{.spec.rules[0].host}') " >> $GITHUB_OUTPUTS
